module.exports = class Data1713926635251 {
    name = 'Data1713926635251'

    async up(db) {
        await db.query(`CREATE TABLE "curation_tag" ("id" character varying NOT NULL, "name" text, "normalized_name" text, "curation_id" character varying, CONSTRAINT "PK_11a55e987b8df439395097fae81" PRIMARY KEY ("id"))`)
        await db.query(`CREATE INDEX "IDX_cf6fce11d2adda475731aca81d" ON "curation_tag" ("curation_id") `)
        await db.query(`CREATE TABLE "curation" ("id" character varying NOT NULL, "token_uri" text, "publisher" text, "hash" text, "timestamp" numeric, "last_updated_at" numeric, "name" text, "description" text, "image" text, "banner_image" text, "properties" jsonb, "metadata" jsonb, CONSTRAINT "PK_de0e4d1c645b4bc2e9a26b9a3f1" PRIMARY KEY ("id"))`)
        await db.query(`CREATE INDEX "IDX_a1ff65d547c257b3c2b8015e3a" ON "curation" ("publisher") `)
        await db.query(`CREATE INDEX "IDX_eedf762f89c27b7573dc9f1be5" ON "curation" ("timestamp") `)
        await db.query(`CREATE INDEX "IDX_69503b75831e186b377ab71c43" ON "curation" ("last_updated_at") `)
        await db.query(`CREATE TABLE "curation_asset" ("id" character varying NOT NULL, "order" numeric, "status" character varying(8), "timestamp" numeric, "approve_at" numeric, "curation_id" character varying, "asset_id" character varying, CONSTRAINT "PK_deb7c8f85e292c8e61759d22980" PRIMARY KEY ("id"))`)
        await db.query(`CREATE INDEX "IDX_ee0912f0404bad60490e0ed008" ON "curation_asset" ("curation_id") `)
        await db.query(`CREATE INDEX "IDX_e521b09aa8277b7b80c0d37b93" ON "curation_asset" ("asset_id") `)
        await db.query(`CREATE INDEX "IDX_53af03ae7139699899387794ed" ON "curation_asset" ("timestamp") `)
        await db.query(`CREATE TABLE "asset_tag" ("id" character varying NOT NULL, "name" text, "normalized_name" text, "asset_id" character varying, CONSTRAINT "PK_bc1024247786d70ae36c809e1ff" PRIMARY KEY ("id"))`)
        await db.query(`CREATE INDEX "IDX_a2780c7e7361aae9795f867079" ON "asset_tag" ("asset_id") `)
        await db.query(`ALTER TABLE "asset" DROP COLUMN "tags"`)
        await db.query(`ALTER TABLE "asset" DROP COLUMN "extra"`)
        await db.query(`ALTER TABLE "asset" ADD "properties" jsonb`)
        await db.query(`ALTER TABLE "hub_manager" ADD "curation" text`)
        await db.query(`ALTER TABLE "asset_metadata_history" DROP COLUMN "metadata"`)
        await db.query(`ALTER TABLE "asset_metadata_history" ADD "metadata" jsonb`)
        await db.query(`ALTER TABLE "asset" DROP COLUMN "metadata"`)
        await db.query(`ALTER TABLE "asset" ADD "metadata" jsonb`)
        await db.query(`ALTER TABLE "curation_tag" ADD CONSTRAINT "FK_cf6fce11d2adda475731aca81d6" FOREIGN KEY ("curation_id") REFERENCES "curation"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`)
        await db.query(`ALTER TABLE "curation_asset" ADD CONSTRAINT "FK_ee0912f0404bad60490e0ed008c" FOREIGN KEY ("curation_id") REFERENCES "curation"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`)
        await db.query(`ALTER TABLE "curation_asset" ADD CONSTRAINT "FK_e521b09aa8277b7b80c0d37b936" FOREIGN KEY ("asset_id") REFERENCES "asset"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`)
        await db.query(`ALTER TABLE "asset_tag" ADD CONSTRAINT "FK_a2780c7e7361aae9795f867079b" FOREIGN KEY ("asset_id") REFERENCES "asset"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`)
    }

    async down(db) {
        await db.query(`DROP TABLE "curation_tag"`)
        await db.query(`DROP INDEX "public"."IDX_cf6fce11d2adda475731aca81d"`)
        await db.query(`DROP TABLE "curation"`)
        await db.query(`DROP INDEX "public"."IDX_a1ff65d547c257b3c2b8015e3a"`)
        await db.query(`DROP INDEX "public"."IDX_eedf762f89c27b7573dc9f1be5"`)
        await db.query(`DROP INDEX "public"."IDX_69503b75831e186b377ab71c43"`)
        await db.query(`DROP TABLE "curation_asset"`)
        await db.query(`DROP INDEX "public"."IDX_ee0912f0404bad60490e0ed008"`)
        await db.query(`DROP INDEX "public"."IDX_e521b09aa8277b7b80c0d37b93"`)
        await db.query(`DROP INDEX "public"."IDX_53af03ae7139699899387794ed"`)
        await db.query(`DROP TABLE "asset_tag"`)
        await db.query(`DROP INDEX "public"."IDX_a2780c7e7361aae9795f867079"`)
        await db.query(`ALTER TABLE "asset" ADD "tags" text`)
        await db.query(`ALTER TABLE "asset" ADD "extra" text`)
        await db.query(`ALTER TABLE "asset" DROP COLUMN "properties"`)
        await db.query(`ALTER TABLE "hub_manager" DROP COLUMN "curation"`)
        await db.query(`ALTER TABLE "asset_metadata_history" ADD "metadata" text`)
        await db.query(`ALTER TABLE "asset_metadata_history" DROP COLUMN "metadata"`)
        await db.query(`ALTER TABLE "asset" ADD "metadata" text`)
        await db.query(`ALTER TABLE "asset" DROP COLUMN "metadata"`)
        await db.query(`ALTER TABLE "curation_tag" DROP CONSTRAINT "FK_cf6fce11d2adda475731aca81d6"`)
        await db.query(`ALTER TABLE "curation_asset" DROP CONSTRAINT "FK_ee0912f0404bad60490e0ed008c"`)
        await db.query(`ALTER TABLE "curation_asset" DROP CONSTRAINT "FK_e521b09aa8277b7b80c0d37b936"`)
        await db.query(`ALTER TABLE "asset_tag" DROP CONSTRAINT "FK_a2780c7e7361aae9795f867079b"`)
    }
}
