version: "3"

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: assethub
      POSTGRES_PASSWORD: postgres
    volumes:
      - .data/postgres:/var/lib/postgresql/data
    ports:
      - "${DB_PORT}:5432"
      # command: ["postgres", "-c", "log_statement=all"]
    shm_size: 1gb

  api:
    image: assethub
    environment:
      - DB_NAME=assethub
      - DB_PORT=5432
      - DB_HOST=db
      - DB_PASS=postgres
      - GQL_PORT=4350
    ports:
      # GraphQL endpoint at port 4350
      - "4350:4350"
    command: ["sqd", "serve:prod"]
    depends_on:
      - db

  processor:
    image: assethub
    environment:
      - DB_NAME=assethub
      - DB_PORT=5432
      - DB_HOST=db
      - DB_PASS=postgres
      - RPC_ENDPOINT=https://rpc-mumbai.polygon.technology
      - ASSETHUB_DEPLOYED_START_BLOCK=46908386
      - IPFS_GATEWAY=https://ipfs.io/ipfs
      - ARWAVE_GATEWAY=https://arweave.net
    ports:
      # prometheus metrics exposed at port 3000
      - "3000:3000"
    command: ["sqd", "process:prod"]
    depends_on:
      - db
