version: "3"

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_PASSWORD: postgres
    volumes:
      - .data/postgres:/var/lib/postgresql/data
    ports:
      - "5432:5432"
      # command: ["postgres", "-c", "log_statement=all"]
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  api:
    image: asset-protocol/indexer-service:latest
    environment:
      - DB_PORT=5432
      - DB_HOST=db
      - DB_USER=postgres
      - DB_DATABASE=postgres
      - DB_PASS=postgres
      - GQL_PORT=3000
      - IPFS_GATEWAY=https://ipfs.io/ipfs
      - ARWAVE_GATEWAY=https://arweave.net
    ports:
      # GraphQL endpoint at port 4350
      - "3000:3000"
    command: ["sqd", "serve:prod"]
    depends_on:
      "db":
        condition: service_healthy
    restart: always

  processor:
    image: asset-protocol/indexer-service:latest
    environment:
      - DB_PORT=5432
      - DB_HOST=db
      - DB_USER=postgres
      - DB_DATABASE=postgres
      - DB_PASS=postgres
      - RPC_ENDPOINT=https://rpc-mumbai.polygon.technology
      - ASSETHUB_DEPLOYED_START_BLOCK=47191328
      - IPFS_GATEWAY=https://ipfs.io/ipfs
      - ARWAVE_GATEWAY=https://arweave.net
    ports:
      # prometheus metrics exposed at port 3000
      - "4350:4350"
    command: ["sqd", "process:prod"]
    depends_on:
      "db":
        condition: service_healthy
